namespace WPT
{
    public enum BoneIndex
    {
        Nose = 0,
        LeftInnerEye = 1,
        LeftEye = 2,
        LeftOuterEye = 3,
        RightInnerEye = 4,
        RightEye = 5,
        RightOuterEye = 6,
        LeftEar = 7,
        RightEar = 8,
        LeftMouth = 9,
        RightMouth = 10,
        LeftShoulder = 11,
        RightShoulder = 12,
        LeftElbow = 13,
        RightElbow = 14,
        LeftWrist = 15,
        RightWrist = 16,
        LeftPinky = 17,
        RightPinky = 18,
        LeftIndex = 19,
        RightIndex = 20,
        LeftThumb = 21,
        RightThumb = 22,
        LeftHip = 23,
        RightHip = 24,
        LeftKnee = 25,
        RightKnee = 26,
        LeftAnkle = 27,
        RightAnkle = 28,
        LeftHeel = 29,
        RightHeel = 30,
        LeftFootIndex = 31,
        RightFootIndex = 32,

        Count,
    }
}